name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test-build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar Testes de Regressão BDD/TDD
        run: npm test

      - name: Compilar e Minificar Build de Produção
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload dos Artefatos de Produção
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
